### ISSUE TITLE
The command fails to run in a non-tty shell

### ISSUE THREAD

**Issue by maxhbr** [amazon-ospo/thunderabsa-cli#4]
If the cli is executed on a non interactive shell it fails to compute the terminal width and thus fails to run:
```
stty: 'standard input': Inappropriate ioctl for device
Traceback (most recent call last):
  File "/usr/local/bin/thundera", line 8, in <module>
    sys.exit(cli())
  File "/opt/thundera-bsa.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/thundera-bsa.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/thundera-bsa.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/thundera-bsa.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/thundera-bsa.venv/lib/python3.8/site-packages/thundera/thundera.py", line 38, in cli
    print(banner_obj)
  File "/opt/thundera-bsa.venv/lib/python3.8/site-packages/terminal_banner/banner.py", line 20, in __str__
    self._reset()
  File "/opt/thundera-bsa.venv/lib/python3.8/site-packages/terminal_banner/banner.py", line 31, in _reset
    self.width = self._calculate_width()
  File "/opt/thundera-bsa.venv/lib/python3.8/site-packages/terminal_banner/banner.py", line 35, in _calculate_width
    width = get_terminal_width()
  File "/opt/thundera-bsa.venv/lib/python3.8/site-packages/terminal_banner/banner.py", line 47, in get_terminal_width
    return int(subprocess.check_output(['stty', 'size']).split()[1])
  File "/opt/python/versions/3.8.11/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/python/versions/3.8.11/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['stty', 'size']' returned non-zero exit status 1.
```

**Comment by ovalba** [comment]
Working on it :)

**Comment by maxhbr** [comment]
I think the issue is https://github.com/amazon-ospo/thunderabsa-cli/blob/main/thundera/thundera.py#L37, which maybe you could find a different way of printing the banner or skip printing the banner in the non-interactive case?

**Comment by maxhbr** [comment]
furthermore is the terminal-banner pretty old (last released Jun 28, 2017) and the corresponding github (https://github.com/martincyoung/terminal_banner) does no longer exist. I hoped to be able to file a bug there.
